#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# 检查是否为Root
[ $(id -u) != "0" ] && { echo "Error: You must be root to run this script"; exit 1; }

# 检查系统信息
if [ ! -z "`cat /etc/issue | grep 'Ubuntu 16'`" ];
    then
        OS='Ubuntu'
    else
        echo "Not support OS(Ubuntu 16), Please reinstall OS and retry!"
        #exit 1
fi

## 初始化安装参数 ##

# 设置静态变量
GITEA_URL='https://dl.gitea.io/gitea/1.4.2/gitea-1.4.2-linux-amd64'
GIT_INIT_UR='https://raw.githubusercontent.com/kaixinguo360/ShellScript/master/git/init/gitea'
GIT_SYSTEMD_URL='https://raw.githubusercontent.com/kaixinguo360/ShellScript/master/git/systemd/gitea.service'
NGINX_CONF='/etc/nginx/sites-enabled/'

# 读取用户输入
read -p '您的网站域名: ' SERVER_NAME

while true :
do
    read -r -p "创建新的Git用户? [Y/n] " input

    case $input in
        [yY][eE][sS]|[yY])
            CREATE_USER='1'
            break
            ;;

	    [nN][oO]|[nN])
            break
            ;;

        *)
        echo "Invalid input..."
        ;;
    esac
done

if [ -n "${CREATE_USER}" ];then
read -p '请设置新的用户名: ' GIT_USER
while true :
do
    read -s -p "请设置新用户 ${GIT_USER} 的密码: " GIT_PASSWORD_1
    echo ''
    read -s -p '再输一遍: ' GIT_PASSWORD_2
    echo ''
    if [ "${GIT_PASSWORD_1}" = "${GIT_PASSWORD_2}" ]; then
        GIT_PW=${GIT_PASSWORD_1}
        break
    else
        echo -e "两次输入密码不一致!\n"
    fi
done
fi

GITEA_ROOT='/home/${GIT_USER}/'


## 正式安装开始 ##

# 新建git用户
HAS_GIT_USER=`cat /etc/passwd|grep -v nologin|grep -v halt|grep -v shutdown|awk -F":" '{ print $1 }' | grep ${GIT_USER}`
if [ ! -n "${HAS_GIT_USER}" ];then
    useradd -m -d /home/${GIT_USER}/gitea-gitea-repositories -s /usr/bin/git-shell ${GIT_USER}
    echo $GIT_USER:$GIT_PW|chpasswd
    if [ $? -eq 0 ]; then
        echo "User '$GIT_USER' has been added to system!"
    else
        echo "Failed to add a user '$GIT_USER' !"
    fi
fi

# 创建数据目录
mkdir -p ${GITEA_ROOT}gitea

# 下载安装Gitea
wget -O ${GITEA_ROOT}gitea/gitea ${GITEA_URL}
chmod +x ${GITEA_ROOT}gitea/gitea

# 创建配置文件
${NGINX_CONF}git << HERE
server {
        listen 80;
        listen [::]:80;

        # SSL configuration
        #
        #listen 443 ssl;
        #listen [::]:443 ssl;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        include my/git/*.conf;

        server_name ${SERVER_NAME};

        location / {
                proxy_pass http://127.0.0.1:3000/;
        }
}

include my/git/*.ser;
HERE

# 创建init.d与systemd配置
wget $GIT_INIT_URL -O /etc/init.d/gitea
chmod +x /etc/init.d/gitea
wget $GIT_SYSTEMD_URL -O /lib/systems/system/gitea.service
chmod +x /lib/systems/system/gitea.service

# 重启Nginx
service nginx restart














